### ISSUE TITLE
sf::Text has no member named 'setFillColor' - Version conflict?

### ISSUE THREAD

**Issue by TheMaverickProgrammer** [TankOs/SFGUI#60]
This is the error I'm getting running cmake:

`/home/maverick/Downloads/SFGUI-master/src/SFGUI/Engines/BREW/Button.cpp:64:8: error: ‘class sf::Text’ has no member named ‘setFillColor’
   text.setFillColor( color );
        ^
CMakeFiles/sfgui.dir/build.make:374: recipe for target 'CMakeFiles/sfgui.dir/src/SFGUI/Engines/BREW/Button.cpp.o' failed
make[2]: *** [CMakeFiles/sfgui.dir/src/SFGUI/Engines/BREW/Button.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/sfgui.dir/all' failed
make[1]: *** [CMakeFiles/sfgui.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
`

I have the latest SFML installed v2.4

**Comment by eXpl0it3r** [comment]
If you have SFML 2.4 installed, then you'd also have `setFillColor`. Check that your SFML headers are updated as well.

**Comment by TheMaverickProgrammer** [comment]
I just realized I installed SFML in a special directory. How can I tell CMAKE where to look for them? That could be the issue.

**Comment by eXpl0it3r** [comment]
If you use SFML 2.4, then you set the `CMAKE_MODULE_PATH` to where `FindSFML.cmake` is located and then set `SFML_ROOT` to where SFML is located. Then `find_package(...)` should find SFML in that location.

**Comment by binary1248** [comment]
Tested and working with SFML 2.5, should also work with SFML 2.4 as @eXpl0it3r mentioned.
